In [1]:
## Libraries 

import sys
sys.path.append('/Users/chris/anaconda/envs/env_pymc3/lib/python3.6/')
sys.path.append('/Users/chris/anaconda/envs/env_pymc3/lib/python3.6/site-packages/')
import pymc3 as pm
import theano
import theano.tensor as T
import numpy as np
import pickle
import imp
import statsmodels.api as sm
import sys

In [2]:
## Old code
sys.path.append('../../data_processing/')

# data manipulation functions. 
import Data_Functions_cdm_mfmri
imp.reload(Data_Functions_cdm_mfmri)
from Data_Functions_cdm_mfmri import get_dataset_cdm_mikes


## Get dftmp for MIDs
dftmp = get_dataset_cdm_mikes(
        modelfit_folder='model_fits',
        models=['rw_w_split_params_exclude_10_gs'],
        return_params=True,
        task=None
        )

../../data_processing/Data_Functions.py:350: RuntimeWarning: Mean of empty slice
  qdf[column] = (value-np.nanmean(value))/np.nanstd(value)
/Users/chris/anaconda/lib/python3.6/site-packages/numpy/lib/nanfunctions.py:1427: RuntimeWarning: Degrees of freedom <= 0 for slice.
  keepdims=keepdims)
../../data_processing/Data_Functions.py:359: RuntimeWarning: Mean of empty slice
  avgmean = np.nanmean(x)#.nanmean()

In [11]:
dftmp2 = dftmp[list(dftmp.columns[[0,1,2]+list(np.arange(43,len(dftmp.columns)))])]

In [12]:
dftmp2.head()

,MID,task,dataset,outcome,AID,ASI,ASI-R,ASIR,Adiff,Age,...,group_just_patients,group_h_l_MASQ.AA,group_h_l_MASQ.AA_clinical,group_h_l_MASQ.AD,group_h_l_MASQ.AD_clinical,group_h_l_MASQ.AS,group_h_l_MASQ.AS_clinical,group_h_l_MASQ.DS,group_h_l_MASQ.DS_clinical,shape_assoc_out_stable
0,cb63,reward,cdm,reward,NaN,10.0,27.0,NaN,NaN,29.0,...,NaN,high_trait,high_trait,high_trait,high_trait,low_trait,low_trait,high_trait,high_trait,blue
1,cb25,pain,cdm,pain,NaN,28.0,66.0,NaN,NaN,29.0,...,MDD,high_trait,MDD,high_trait,MDD,high_trait,MDD,high_trait,MDD,green
2,cb74,pain,cdm,pain,NaN,40.0,97.0,NaN,NaN,29.0,...,MDD,high_trait,MDD,high_trait,MDD,high_trait,MDD,high_trait,MDD,green
3,cb73,reward,cdm,reward,NaN,22.0,68.0,NaN,NaN,999.0,...,MDD,high_trait,MDD,high_trait,MDD,high_trait,MDD,high_trait,MDD,blue
4,cb75,pain,cdm,pain,NaN,33.0,75.0,NaN,NaN,22.0,...,MDD,high_trait,MDD,high_trait,MDD,high_trait,MDD,high_trait,MDD,green

In [13]:
dftmp2.to_csv('../data_tables/participant_table_2_11_19.csv')

In [14]:
import pandas as pd
pd.read_csv('../data_tables/participant_table_2_11_19.csv',index_col=0).head()

,MID,task,dataset,outcome,AID,ASI,ASI-R,ASIR,Adiff,Age,...,group_just_patients,group_h_l_MASQ.AA,group_h_l_MASQ.AA_clinical,group_h_l_MASQ.AD,group_h_l_MASQ.AD_clinical,group_h_l_MASQ.AS,group_h_l_MASQ.AS_clinical,group_h_l_MASQ.DS,group_h_l_MASQ.DS_clinical,shape_assoc_out_stable
0,cb63,reward,cdm,reward,NaN,10.0,27.0,NaN,NaN,29.0,...,NaN,high_trait,high_trait,high_trait,high_trait,low_trait,low_trait,high_trait,high_trait,blue
1,cb25,pain,cdm,pain,NaN,28.0,66.0,NaN,NaN,29.0,...,MDD,high_trait,MDD,high_trait,MDD,high_trait,MDD,high_trait,MDD,green
2,cb74,pain,cdm,pain,NaN,40.0,97.0,NaN,NaN,29.0,...,MDD,high_trait,MDD,high_trait,MDD,high_trait,MDD,high_trait,MDD,green
3,cb73,reward,cdm,reward,NaN,22.0,68.0,NaN,NaN,999.0,...,MDD,high_trait,MDD,high_trait,MDD,high_trait,MDD,high_trait,MDD,blue
4,cb75,pain,cdm,pain,NaN,33.0,75.0,NaN,NaN,22.0,...,MDD,high_trait,MDD,high_trait,MDD,high_trait,MDD,high_trait,MDD,green